services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  notes-service:
    build: ./notes-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    volumes:
      - ./notes-service:/app
      - /app/node_modules